name: openfe_gromacs
channels:
  - conda-forge/label/openff-interchange_rc 
  - conda-forge
dependencies:
  - openfe
  - compilers
  - mpi4py
  - gromacs
  - pytest
  - pytest-xdist
  - pytest-cov
  - openff-interchange =0.4
